# Generated by Django 2.2.4 on 2019-08-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190827_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
