# Generated by Django 2.2.4 on 2019-08-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190827_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
    ]
