# Generated by Django 2.2.4 on 2019-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190827_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
