# Generated by Django 2.2.4 on 2019-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='validate_field',
            field=models.BooleanField(default=True),
        ),
    ]
