# Generated by Django 2.2.4 on 2019-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phoneotp_validate_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='validate_field',
            field=models.BooleanField(default=False),
        ),
    ]
