# Generated by Django 2.2.4 on 2019-09-03 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190902_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(max_length=9),
            preserve_default=False,
        ),
    ]
